# Generated by Django 3.1.3 on 2020-12-08 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('branch_code', models.CharField(max_length=10, verbose_name='Branch Code')),
                ('branch_licence_no', models.CharField(max_length=255, verbose_name='Branch Licence No')),
                ('branch_district', models.CharField(max_length=255, verbose_name='Branch District')),
                ('branch_opening_date', models.DateField(default=datetime.date(2020, 12, 8), verbose_name='Branch Opening Date')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Name')),
                ('employees_father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('employee_mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('employee_date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('employee_nid', models.CharField(max_length=25, verbose_name='NID')),
                ('employee_birth_registration_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth Registration Number')),
                ('employee_tin_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='TIN Number')),
                ('employee_mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('employee_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('employee_present_address', models.TextField(max_length=2500, verbose_name='Present Address')),
                ('employee_permanent_address', models.TextField(max_length=2500, verbose_name='Permanent Address')),
                ('employee_joining_date', models.DateField(verbose_name='Date of Joining')),
                ('employee_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.branchdetails', verbose_name='Branch Name')),
                ('employee_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.gender', verbose_name='Gender')),
            ],
        ),
    ]
