# Generated by Django 3.1.3 on 2020-12-08 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdetails',
            name='branch_opening_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 8, 16, 55, 27, 683323, tzinfo=utc), verbose_name='Branch Opening Date'),
        ),
    ]
