# Generated by Django 3.1.3 on 2020-12-11 19:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_auto_20201208_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdetails',
            name='branch_opening_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 19, 2, 40, 996747, tzinfo=utc), verbose_name='Branch Opening Date'),
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
